### ISSUE TITLE
Could image-to-internal-storage.sh pipe image directly to dd?

### ISSUE THREAD

**Issue by m-col** [dirkjanbuter/pinephone-commands#1]
Hi! Thanks for compiling these snippets together from the forums, they are very useful!

Have you tested image-to-internal-storage.sh? It flashes and boots fine? Did you get a nice performance boost vs booting from the SD card?

I wonder if the script could download the image, decompress and flash the eMMC without writing the image to the SD card. My concern would be a lack of space on the SD card, given that the ubuntu-touch image is *huge*. Perhaps something like this (not tested):

```
wget https://ci.ubports.com/job/rootfs/job/rootfs-pinephone/lastSuccessfulBuild/artifact/ubuntu-touch-pinephone.img.gz | gunzip | sudo dd of=/dev/mmcblk2 bs=4096 status=progress
```
Ref: https://stackoverflow.com/questions/20702812/how-to-download-a-linux-image-unzip-it-and-write-it-to-an-sd-card-in-one-line

**Comment by dirkjanbuter** [comment]
Thank you for your feedback! I fixed some more issues. It should work with a small SD card now too.
I did not noticed a performance boost, but used a SanDisk Extreme Plus DS card (fast).

**Comment by m-col** [comment]
Great! I'll hopefully get some time to play with it again soon.
